// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BY.Data.Models;

public partial class BookingDetail
{
    public int BookingDetailId { get; set; }

    public int? ScheduleId { get; set; }

    public int? BookingId { get; set; }

    public decimal? Price { get; set; }

    public decimal? Amount { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Schedule Schedule { get; set; }
}