// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BY.Data.Models;

public partial class Court
{
    public int CourtId { get; set; }

    public string Name { get; set; }

    public bool? IsInUse { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}