// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BY.Data.Models;

public partial class Court
{
    public int CourtId { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }

    public bool? IsInUse { get; set; }

    public string Type { get; set; }

    public string Color { get; set; }

    public string Address { get; set; }

    public string SurfaceType { get; set; }

    public string Area { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}