// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BY.Data.Models;

public partial class Schedule
{
    public int ScheduleId { get; set; }
    [Required(ErrorMessage = "Chose court")]
    public int CourtId { get; set; }
    [Required]
    public TimeOnly From { get; set; }
    [Required]
    public TimeOnly To { get; set; }
    [Required]
    public decimal Price { get; set; }
    [Required]
    public DateOnly Date { get; set; }

    public string Notes { get; set; }

    public string StaffCheck { get; set; }

    public string Event { get; set; }

    public bool? IsBooked { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual Court Court { get; set; }
}