// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BY.Data.Models;

public partial class Booking
{
    public int ScheduleId { get; set; }

    [Required(ErrorMessage = "The Court field is required")]
    public int? CourtId { get; set; }

    [Required]
    public TimeOnly? From { get; set; }

    [Required]
    public TimeOnly? To { get; set; }

    [Required]
    public decimal? Price { get; set; }

    [Required]
    public DateTime? Date { get; set; }

    [Required]
    public bool? IsBooked { get; set; } = false;
    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual Court Court { get; set; }
}
