// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BY.Data.Models;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public int? CourtId { get; set; }

    public TimeOnly? From { get; set; }

    public TimeOnly? To { get; set; }

    public decimal? Price { get; set; }

    public DateOnly? Date { get; set; }

    public string Notes { get; set; }

    public string StaffCheck { get; set; }

    public string Event { get; set; }

    public bool? IsBooked { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();
}